name: Keep Streamlit Alive

on:
  schedule:
    - cron: "0 */6 * * *" # Pings your app every 6 hours
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I https://json-app-cdf.streamlit.app/
